# EQUAL WEIGHT CONFIGURATION

CGPA_WEIGHT = 0.20
SKILLS_WEIGHT = 0.20
PROJECT_WEIGHT = 0.20
INTERNSHIP_WEIGHT = 0.20
HACKATHON_WEIGHT = 0.20


# MAXIMUM SCORES

MAX_CGPA_SCORE = 20
MAX_SKILL_SCORE = 20
MAX_PROJECT_SCORE = 20
MAX_INTERNSHIP_SCORE = 20
MAX_HACKATHON_SCORE = 20