# AIRA WEIGHT CONFIGURATION

CGPA_WEIGHT = 0.30
SKILLS_WEIGHT = 0.25
PROJECT_WEIGHT = 0.20
INTERNSHIP_WEIGHT = 0.15
HACKATHON_WEIGHT = 0.10


# MAXIMUM SCORES

MAX_CGPA_SCORE = 30
MAX_SKILL_SCORE = 25
MAX_PROJECT_SCORE = 20
MAX_INTERNSHIP_SCORE = 15
MAX_HACKATHON_SCORE = 10eholder
